### ISSUE TITLE
ImportError: cannot import name 'isin' from 'jax._src.numpy.lax_numpy'

### ISSUE THREAD

**Issue by dsm-72** [bunnech/jkonet#1]
Cloned repo, followed setup, ran example and got:
```bash
$ python main.py --out_dir results --config_folder configs --task semicircle
2022-08-01 12:44:45.944149: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-08-01 12:44:45.960144: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-08-01 12:44:45.961190: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/home/USER/projects/jkonet/main.py", line 7, in <module>
    import flax
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/flax/__init__.py", line 20, in <module>
    from . import linen
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/flax/linen/__init__.py", line 20, in <module>
    from .activation import (celu, elu, gelu, glu, leaky_relu, log_sigmoid,
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/flax/linen/activation.py", line 46, in <module>
    from flax.linen.module import Module, compact
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/flax/linen/module.py", line 32, in <module>
    from jax._src.numpy.lax_numpy import isin
ImportError: cannot import name 'isin' from 'jax._src.numpy.lax_numpy' (/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/jax/_src/numpy/lax_numpy.py)
```

**Comment by bunnech** [comment]
Seems to be a version problem of Flax. I suggest updating it.

**Comment by dsm-72** [comment]
@bunnech this is the version from the requirments file. What version should I use?

**Comment by dsm-72** [comment]
After running
```
pip install --upgrade flax
```
I now get

```bash
$ python main.py --out_dir results --config_folder configs --task semicircle
Traceback (most recent call last):
  File "/home/USER/projects/jkonet/main.py", line 13, in <module>
    import wandb
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/wandb/__init__.py", line 27, in <module>
    from wandb import sdk as wandb_sdk
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/wandb/sdk/__init__.py", line 9, in <module>
    from .wandb_init import _attach, init  # noqa: F401
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 31, in <module>
    from .backend.backend import Backend
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/wandb/sdk/backend/backend.py", line 21, in <module>
    from ..interface.interface import InterfaceBase
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 21, in <module>
    from wandb.proto import wandb_internal_pb2 as pb
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/wandb/proto/wandb_internal_pb2.py", line 15, in <module>
    from wandb.proto import wandb_base_pb2 as wandb_dot_proto_dot_wandb__base__pb2
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/wandb/proto/wandb_base_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/home/USER/anaconda3/envs/jko/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).

More information: https://developers.google.com/protocol-buffers/docs/news/2022-05-06#python-updates
```
